only_player: "å‘½ä»¤ä»…é€‚ç”¨äºç©å®¶æ‰§è¡Œ"
not_found_model: "æ‰¾ä¸åˆ°æ¨¡å‹"
not_format: "æ ¼å¼é”™è¯¯"
#æœ€å°ä»·æ ¼
min-price: 90
#æœ€å¤§ä»·æ ¼
max-price: 320
menu:
  title: "ğŸ“¦ æ—¶è£…å•†åº— #"
  last:
    name: "â¬…ï¸ &fä¸Šä¸€é¡µ"
    icon: lime_stained_glass_pane
    data: 10020
    slot: 45
  next:
    name: "\uD83D\uDD1C &fä¸‹ä¸€é¡µ"
    icon: lime_stained_glass_pane
    data: 10020
    slot: 53
  back:
    name: "â¬…ï¸ &fè¿”å›"
    icon: lime_stained_glass_pane
    data: 10020
    command: dc open menu %player_name%
    slot: 49
  announcement:
    name: "ğŸ”ˆ&få…¬å‘Š"
    icon: white_stained_glass_pane
    data: 10020
    slot: 48
    lore: []
